### ISSUE TITLE
Better support for large payloads

### ISSUE THREAD

**Issue by jlashmet** [oci-pronghorn/GreenLightning#51]
Hi,

I'm working on moving a REST API from Tomcat to GreenLightning.  On average, the API takes in a list of 100 items to update, but occasionally can receive requests with 1000 or even 10000 items.  Because of this, I have to set the max request size to 600000 and the heap size to 12GB.  Even when I do this, I have to set the concurrency parameters very low or I run out of heap.  Also with such a large heap, garbage collection times are unacceptably long.  Are there any ways to get around this, or perhaps any future plans for streaming chunks of the request through to be processed separately?

Thanks,
Jason

**Comment by nathantippy** [comment]
Please test with new release today.  Max request now uses less because it can slice up the data.  We also have set max queue in for messages in flight setting this small also helps reduce memory.  Also look into new slipstream examples.

**Comment by nathantippy** [comment]
What is you limit before you assume this caller is a hacker or bad player?
